config/routes.rb
Rails.application.routes.draw do
  get "/", to: "application#homepage", as: "homepage"
  get "/login", to: "sessions#login"
  post "/login", to: "sessions#process_login"
  get "/logout", to: "sessions#logout"
  get "/about", to: "sessions#about", as: "about"


  resources :states
  resources :park_states
  resources :parks
  resources :trails do 
    resources :hikes, only: [:new, :create, :show, :destroy]
  end 
    
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hike.rb
class Hike < ApplicationRecord
    belongs_to :user 
    belongs_to :trail 
    
    validates :name, presence: true, uniqueness: true


    def self.average_rating_of_all_hikes 
        result = Hike.all.map{|hike| hike.user_rating}
        sum = result.reduce(:+)
        x = result.count
        sum/x
    end 

end

app/models/park.rb
class Park < ApplicationRecord
    has_many :trails
    has_many :park_states
    has_many :states, through: :park_states

    def has_waterfalls? 
        if self.waterfalls == true 
            return "Yes"
        else 
            return "No"
        end 
    end 

end

app/models/park_state.rb
class ParkState < ApplicationRecord
    belongs_to :park 
    belongs_to :state
end

app/models/state.rb
class State < ApplicationRecord
    has_many :park_states
    has_many :parks, through: :park_states

    def self.sort_by_first_letter 
        State.order('name ASC')
    end 
end

app/models/trail.rb
class Trail < ApplicationRecord
    has_many :hikes 
    has_many :users, through: :hikes
    belongs_to :park

    validates :name, presence: true, uniqueness: true

    def average_trail_rating  
        result = self.hikes.map{|hike| hike.user_rating}
        sum = result.reduce(:+)
        x = result.count
        sum/x
    end 

    def self.highest_rated_trail 
        # looks through all trails, finds the average trail rating in a new array then find the highest value from that array and return the trail object that has it. 
        max = Trail.all.map{|trail| trail.average_trail_rating}.max
        Trail.all.each do |trail|
            if trail.average_trail_rating == max 
                return trail
            end 
        end 
        
    end 

    def self.lowest_rated_trail 
        # looks through all trails, finds the average trail rating in a new array then find the lowest value from that array and return the trail object that has it. 
        min = Trail.all.map{|trail| trail.average_trail_rating}.min
        Trail.all.each do |trail|
            if trail.average_trail_rating == min 
                return trail
            end 
        end 

    end 

    def total_hikers 
        self.hikes.count
    end 

    def self.all_total_hikes 
        self.all.map{|trail| trail.hikes}.count
    end 



    def self.sort_by_first_letter 
        Trail.order('name ASC')
    end 


end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :hikes 
    has_many :trails, through: :hikes
    
    validates :name, presence: true, uniqueness: {case_sensitive: false}
    validates :password, presence: true, length: { minimum: 4 }

    def states 
        self.trails.each do |trail|
            trail.park.states.each do |state|
                return state
            end 
        end 
    end 

    def total_distance_hiked 
        self.trails.map{|trail| trail.distance_of_trail}.sum
    end 

    def total_elevation_gain 
        self.trails.map{|trail| trail.elevation}.sum 
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        @current_user = User.find_by(id: session[:user])
    end 

    def logged_in?
        !!current_user 
    end 

    def authorized
        redirect_to login_path unless logged_in? 
    end 

    def homepage 
        render :homepage
    end 

    def about 
    end 


end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController
    before_action :find_hike, only: [:show]
    before_action :authorized

    def show 
    end 

    def new 
        if current_user
            @hike = Hike.new
        else 
            redirect_to login_path 
        end 
    end 

    def create 
        @hike = Hike.new
        @hike.name = params[:hike][:name]
        @hike.user_rating = params[:hike][:user_rating]
        @hike.user_id = current_user.id
        @hike.trail_id = params[:trail_id]
        @hike.save
        redirect_to trail_hike_path(@hike.trail_id, @hike.id)
    end 

    private 

    def find_hike 
        @hike = Hike.find(params[:id])
    end 

    # def hike_params 
    #     params.require(:hike).permit(:name, :user_rating, :user_id, :trail_id)
    # end 


end

app/controllers/park_states_controller.rb
class ParkStatesController < ApplicationController
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController

    def show 
        @park = Park.find(params[:id])
    end 

    def index 
        @parks = Park.all
    end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def about
    end 

    def login 
    end 

    def process_login
        username = params[:name]
        @user = User.find_by(name: username)
        if @user && @user.authenticate(params[:password])
            session["user"] = @user.id
            flash[:message] = "User logged in"
            redirect_to states_path
        else 
            flash.now[:error] = "No user found with that name and password"
            render :login
        end 
    end 

    def logout
        session.clear
        redirect_to login_path
    end 
end

app/controllers/states_controller.rb
class StatesController < ApplicationController

    def show 
        @state = State.find(params[:id])
    end 

    def index 
        @states = State.all.sort_by_first_letter
    end 


end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController

    def show 
        @trail = Trail.find(params[:id])
    end 

    def index 
        @trails = Trail.all
    end 


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:show, :edit, :update, :destroy]
    before_action :authorized, except: [:new, :create]

    def new 
        @user = User.new
    end 

    def create 
        @user = User.create(user_params)
        if @user.valid?
            redirect_to states_path
        else 
            render :new 
        end
    end 

    def edit 
    end 

    def update 
        @user.update(user_params)
        redirect_to user_path(@user)
    end 

    def show 
    end 
    
    def index 
        @users = User.all
    end 
    
    def destroy 
        @user.destroy 
        redirect_to login_path
    end 

    private 

    def find_user
        @user = User.find(params[:id])
    end 

    def user_params 
        params.require(:user).permit(:name, :password)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hikes_helper.rb
module HikesHelper
end

app/helpers/park_states_helper.rb
module ParkStatesHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hikes/new.html.erb
<div class='login'>

<h1> New Hike </h1>

<%= form_for @hike, url:trail_hikes_path do |f| %>
    <%= f.label 'Name your Hike!' %>
    <%= f.text_field :name %>
    <%= f.label "Rate the this trail" %>
    <%= f.select :user_rating, options_for_select(0..10) %>

    <%= f.submit %>
<% end %>

</div>

app/views/hikes/show.html.erb
<div class='login'>

    <h1 class='title is-2'><%= @hike.name %></h1>
    <p>My trail rating: <%= @hike.user_rating %></p>

    <br><br>

    <h4 class='title is-5'>Trail Information:</h4>
        <div>Trail: <%= link_to @hike.trail.name, trail_path(@hike.trail.id) %></div>
        <div>Park: <%= link_to @hike.trail.park.name, park_path(@hike.trail.park.id) %></div>
        <div>Trail distance: <%= "#{@hike.trail.distance_of_trail} miles" %></div>
        <div>Trail elevation gain: <%= "#{@hike.trail.elevation} feet" %></div>
        <div>Trail difficulty: <%= "#{@hike.trail.difficulty}" %></div>
        <div>Average trail rating: <%= "#{@hike.trail.average_trail_rating}" %></div>


<br>

    <%= link_to "Go back to National Parks", parks_path, class: "button is-info" %>


</div>

app/views/parks/index.html.erb
<div class='login'>
<h1 class='title is-1'>National Parks</h1>

<ul>
    <% @parks.each do |park| %>
        <li><%= link_to park.name, park_path(park.id) %></li>
    <% end %>
</ul>

</div>

app/views/parks/show.html.erb
<div class='login'>
<h1 class='title is-2'><%= @park.name %></h1>

<p>Park Information:</p>
<div><%= @park.park_info %></div>

<br>

<p>Waterfalls? <%= @park.has_waterfalls? %></p>

<br>

<p>List of trails:</p> 
<ul>
    <% @park.trails.each do |trail| %>
        <li><%= link_to trail.name, trail_path(trail.id) %></li>
    <% end %>
</ul>
</div>

app/views/states/index.html.erb
<div class='login'>
<h1 class='title is-1'>States</h1>

<% if flash[:message] %>
    <div class='error'><%= flash[:message] %></div>
<% end %>

<ul> 
    <% @states.each do |state| %>
        <li><%= link_to state.name, state_path(state.id) %></li>
    <% end %>
</ul>

</div>

app/views/states/show.html.erb
<div class='login'>
<h1 class='title is-2'><%= @state.name %></h1>

<h3>National Parks:<h3>

<br>

<ul> 
    <% @state.parks.each do |park| %>
        <li><%= link_to park.name, park_path(park.id) %></li>
    <% end %>
</ul>
</div>

app/views/trails/index.html.erb
<div class='login'>
<h1 class='title is-1'>All trails</h1>
<%
=begin%>
 <%= select("trail", "name", Trail.all.collect(&:name).sort) %> 
<%
=end%>

<ul>
    <% @trails.each do |trail| %>
        <li><%= link_to trail.name, trail_path(trail.id) %></li>
    <% end %>
</ul>
</div>

app/views/trails/show.html.erb
<div class='login'>

<h1 class='title is-2'><%=@trail.name%></h1>

<h4>Trail Information:</h4>
    <div>Park: <%= link_to @trail.park.name, park_path(@trail.park.id) %></div>
    <div>Trail distance: <%= "#{@trail.distance_of_trail} miles " %></div>
    <div>Trail elevation: <%= "#{@trail.elevation} feet above sea level" %></div>
    <div>Trail difficulty: <%= @trail.difficulty.capitalize %></div>
    <%
=begin%>
 <div>Average trail rating: <%= @trail.average_trail_rating %></div> 
<%
=end%>

<div>Number of Hikers that have completed this trail: <%= @trail.total_hikers %></div>

<br>

<%= link_to "Add this Hike", new_trail_hike_path(@trail.id), class: "button is-info" %>

</div>

app/views/users/edit.html.erb
<h1> Edit User </h1>

<%= form_for @user do |f| %>
    <%= f.label 'Enter your username:' %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>
<ul>
    <% @users.each do |user| %>
        <li><%= link_to user.name, user_path(user.id) %></li>
    <% end %>
</ul>

app/views/users/new.html.erb
<div class='login'>
    <h1 class='title is-5'> Create a new user </h1>

    <% if @user.errors %>
        <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>

    <%= form_for @user do |f| %>
        <%= f.label 'Enter your username:' %>
        <%= f.text_field :name %>
        <%= f.label :password, "Password" %>
        <%= f.password_field :password %>
        <%= f.submit %>
    <% end %>
</div>

app/views/users/show.html.erb
<div class='login'>
<h1 class='title is-1'><%= @user.name %></h1>

<div>All my Hikes:
    <ul>
        <% @user.hikes.each do |hike| %>
            <li><%= link_to hike.name, trail_hike_path(hike.trail_id, hike.id) %></li>
        <% end %>
    </ul>

</div>


<br><br>

<div>Total distance I've hiked: <%= "#{@user.total_distance_hiked} miles" %></div>
<div>Total Elevation gain: <%= "#{@user.total_elevation_gain} feet" %></div>
</div>

app/views/users/tempshow.html.erb
<div>Trails that I have hiked: 
    <ul>
        <% @user.trails.each do |trail| %>
            <li><%= link_to trail.name, trail_path(trail.id) %></li>
        <% end %>
    </ul>
</div>

<div>Parks I have been to: 
    <ul>
        <% @user.trails.each do |trail| %>
            <li><%= link_to trail.park.name, park_path(trail.park.id) %></li>
        <% end %>
    </ul>
</div>

<div>States I've visited: 
    <ul>
        <li><%= link_to @user.states.name, state_path(@user.states.id) %></li>
    </ul>
</div>

<div>Number of hikes I've done: 
    <%= @user.hikes.count %>
</div>